apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: 203520860987.dkr.ecr.us-east-1.amazonaws.com/java_dev:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://employee.cluster-cc9i8ug04gru.us-east-1.rds.amazonaws.com:3306/employee
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: Admin123
